### ISSUE TITLE
Script should handle case when `name` argument references random_pet resource

### ISSUE THREAD

**Issue by betsy-lichtenberg** [msampathkumar/MagicModules-TerraformTools#7]
[`random_pet`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) is a commonly used Terraform resource for randomizing resource names to prevent duplicates.

This [sample](https://paste.googleplex.com/4808974189723648) uses `random_pet` to help ensure that the new bucket resource has a unique name. 

Similarly, [here is another sample](https://paste.googleplex.com/5196901742804992 )that uses `random_pet` for many of the resource names.

When I run tftools, I get the following parsing error:

```

	Error: Failed to find name for the following line
		--->[name                        = "bucket-${random_pet.suffix.id}"]<---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 125, in get_resource_name
    name = re.findall(resource_name_regex_pattern, text)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tftools", line 11, in <module>
    load_entry_point('tftools==1.0', 'console_scripts', 'tftools')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/tftools.py", line 35, in main
    convert2erb.parse_user_args(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 341, in parse_user_args
    convert_to_erb(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 306, in convert_to_erb
    tf_resource_parser(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 114, in wrap_func
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 193, in tf_resource_parser
    rname = get_resource_name(resource_name_lines[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tftools-1.0-py3.7.egg/convert2erb.py", line 133, in get_resource_name
    raise Exception("Parsing Error!")
Exception: Parsing Error!
```

**Comment by betsy-lichtenberg** [comment]
I think we can close this issue and handle it with documentation.

Something like this:

In your `.tf` file, don't include the `random_pet` resource or any other resource for generating custom resource names. These resources are unnecessary in Magic Modules, because Magic Modules automatically generates unique names when testing resources that have the `vars` tag, as follows:

```
resource "google_compute_backend_bucket" "static" {
  name        = "<%= ctx[:vars]['backend_bucket_name'] %>"
  bucket_name = google_storage_bucket.static.name
  enable_cdn  = true
}
```
